Fixed Win Server 2019 node definition and added NXOSv 9500
CiscoDevNet/cml-community pull request #26
Opened 2022-11-21 16:14 UTC by CML-TAC

Changes
Fixed Win Server 2019 node definition.
Added NXOSv 9500 with 128 ports
Deleted duplicate readme for palo alto

2022-11-24 10:48 UTC, xorrkaz commented on node-definitions/cisco/NXOSv 9500 128 ports/readme.md
> +*`nxosv9500-148.yaml` - Nexus 9500v with 128 ports node definition
This says 128 switch ports, but your node def talks about 148.  Ultimately, I do see that it is 148 (64 + 16 + 32 + 36).  So it's probably just this typo that needs to be fixed.

2022-11-24 10:48 UTC, xorrkaz requested changes
See comment.

2022-11-24 16:33 UTC, tmikuska commented on node-definitions/cisco/NXOSv 9500 128 ports/readme.md
> +# NXOSv 9500 with 128 ports
```suggestion
# NXOSv 9500 with 148 ports
```

2022-11-24 16:37 UTC, tmikuska commented on node-definitions/cisco/NXOSv 9500 128 ports/readme.md
> +# NXOSv 9500 with 128 ports
I thought that I would be able to apply a suggestion but no permissions here.

2022-11-26 12:52 UTC, xorrkaz approved these changes
Looks good.

2022-11-26 12:53 UTC, merged