Adding Watchguard FireboxV all version
CiscoDevNet/cml-community pull request #40
Opened 2024-05-17 15:26 UTC by Acronychal

Tested on CML 2.6 & 2.7

2024-05-17 15:27 UTC, Acronychal commented
Watchguard FireboxV node definition pull request

2024-05-18 15:33 UTC, Acronychal commented
They do have a dimension server that runs off a .ova/qcow2. I can test and integrate that too. I've not had the need to use it yet.

2024-05-18 15:34 UTC, xorrkaz commented
You don't have to integrate if you don't want to, but it might make sense to put this in its own subdirectory

2024-05-18 15:51 UTC, Acronychal commented
I agree.

2024-05-19 16:55 UTC, xorrkaz requested changes

2024-05-19 16:55 UTC, xorrkaz commented on node-definitions/watchguard/README.md
Can you change this into an overall Watchguard readme, and then move this file to the fireboxv subdir?

2024-05-21 11:14 UTC, Acronychal commented on node-definitions/watchguard/README.md
Done.

2024-05-21 14:12 UTC, xorrkaz commented on node-definitions/watchguard/README.md
Looks good to me!

2024-05-21 14:13 UTC, xorrkaz approved these changes

2024-05-22 15:37 UTC, merged